### ISSUE TITLE
Can't redirect Playlists/Channels.

### ISSUE THREAD

**Issue by MintMain21** [kleutzinger/invidious-redirect#1]
It seems this only works with videos, which is nice, but I think this would make a great safety net so people don't have to constantly replace the domain they use in their redirects. 

It's a good idea to allow redirects to more than just videos, so that people could easily be redirected after searching a channel or something.

**Comment by kleutzinger** [comment]
closed by https://github.com/kleutzinger/invidious-redirect/commit/2803c8359a6fca0a936ace870d32bed4dd0abaa4
